### ISSUE TITLE
Setup Error with sample data on Magento 2.1 EE

### ISSUE THREAD

**Issue by dooblem** [magento/magento2-sample-data#25]
Hello,

I'm unable to setup sample data under Magento EE 2.1.
`bin/magento sampledata:deploy` went well, but when running `bin/magento setup:upgrade` :

```
...
Module 'Magento_Eway':
Module 'Magento_Fedex':
Module 'Magento_TargetRule':
Module 'Magento_GiftCardAccount':
Module 'Magento_GiftCardImportExport':
Module 'Magento_Weee':
Module 'Magento_GiftRegistry':
Module 'Magento_GiftMessage':
Module 'Magento_GiftMessageStaging':
Module 'Magento_CatalogStaging':
Module 'Magento_GiftRegistrySampleData':
Installing data... PHP Fatal error:  Uncaught Error: Call to a member function getData() on boolean in /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/module-gift-registry-sample-data/Model/GiftRegistry.php:192
Stack trace:
#0 /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/module-gift-registry-sample-data/Model/GiftRegistry.php(144): Magento\GiftRegistrySampleData\Model\GiftRegistry->generateData(Array)
#1 /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/module-gift-registry-sample-data/Setup/Installer.php(30): Magento\GiftRegistrySampleData\Model\GiftRegistry->install(Array)
#2 [internal function]: Magento\GiftRegistrySampleData\Setup\Installer->install()
#3 /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/framework/App/State.php(171): call_user_func_array(Array, Array)
#4 /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/framework/Setup/SampleData/Executor.php(50): Magento\Framework\App\State->emulateAreaCode('setup', Array)
#5 /var/www/magento_deploy/r in /var/www/magento_deploy/releases/20160812150332/src/vendor/magento/module-gift-registry-sample-data/Model/GiftRegistry.php on line 192
```

It's working fine under Magento 2.1 CE.

Thanks in advance,
Marc

**Comment by jthn** [comment]
I had to replace line 192 in `vendor/magento/module-gift-registry-sample-data/Model/GiftRegistry.php` with the following:

```
        $address = $customer->getDefaultBillingAddress();
        if(is_bool($address)) {
            return [];
        }
        $address = $address->getData();
```

I was able to complete the upgrade task.  I'm unsure what this might affect, but I was able to get sample data loaded.

**Comment by MorganGonzales** [comment]
This problem occurs on fresh installation of Magento 2.1.2. Any suggested fix aside from @jthn?

@jthn Thanks for this quick fix bro. But Magento has to verify this as it might affect other functionalites which I hope it won't.

![screen shot 2016-11-03 at 5 51 38 pm](https://cloud.githubusercontent.com/assets/14289402/19961567/4e24c2f2-a1ee-11e6-8438-53b46e8b7cb6.png)

**Comment by BenSpace48** [comment]
@jthn If you do use that fix I'd advise overriding that file from your theme if possible instead of editing it in the vendor directory as you'll likely lose your changes when you update.

**Comment by dooblem** [comment]
Any update ? I'm still using @jthn  patch to make it work...

**Comment by bery** [comment]
Same issue here. Can you provide any update?

**Comment by diazwatson** [comment]
@jthn why you don't make a pull request with it? :)

**Comment by JRhyne** [comment]
Same issue occurs with EE 2.2.4. The solution still works, though.

**Comment by NikolasSumrak** [comment]
@diazwatson Gift registry doesn't included in Open Source, and it doesn't present in this repo. It's enterprise module, and sample data for Gift registry also enterprise

**Comment by diazwatson** [comment]
I also had this issue last week while working on a project.
I didn't have time to set a fresh environment and debug it so I used @jthn workaround to skip it and carry on installing.
Now that I am looking at it on a fresh environment, it just work as expected. :(
I have tested this in 2.2.4, 2.2.5 and 2.2.6

Can anybody provide more info?

**Comment by SyedMuneebb** [comment]
Thank you guys for providing a solution for installing sample data in Magento 2 store. KUDOS to all.

Well, here's a guide on Magento 2 sample data that can help: [How to Install Magento 2 Sample Data](https://magenticians.com/install-magento-2-sample-data/)

Thanks!
